#!/bin/zsh
setopt NO_FUNCTION_ARGZERO LOCAL_OPTIONS;

local SF=${(%):-%x};
local SD=`dirname $SF`;

() {
	setopt LOCAL_OPTIONS LOCAL_TRAPS;

##																									\e[m
##	cdt [options]
##		Creates a temporary directory and cd's into it, temporary directories are not cleaned
## 		automatically.
##																									\e[m
##		\e[31;1moptions\e[m
##			-h		  Shows this help information
##			-v		  Increases verbosity, may be repeated multiple times
##

	# Ends the function call with an exit status of 128 + $1
	TRAPABRT() { return $(( 128 + $1 )); }

	# Prints out the help for this command, as formatted above with lines that start out with ##<tab>
	help() {
		print -l "`cat $SF | \pcregrep -o1 '^##\t(.+)$'`";
		kill -ABRT $$;
	}

	# Prints out a red error line of all arguments passed in, followed by the help contents
	error() {
		echo "\e[31;1m$@\e[m";
		help;
	}

	# Prints out args $2..$N if verbosity is at least the value of $1
	vmsg() {
		[[ $1 > $VERBOSITY ]] &&
			return;
		shift;	# Drop $1
		echo $*;
	}

	# Parse the options passed in, this needs to match the options listed in the help file, see `man zshmodule` for details
	zparseopts -D -E v+=VERBOSITY h=HELP ||
		help;

	# Capture the verbosity number (number of -vvv's)
	VERBOSITY=${#VERBOSITY}

	# Display help if requested
	[[ "$HELP" ]] &&
		help;


	# Called on exit from this point forward
	on_exit() {
		# Any exit code goes here as appropriate
	}
	trap on_exit EXIT;

	# Command code starts here


} "$@";
