#!/bin/zsh
setopt NO_FUNCTION_ARGZERO LOCAL_OPTIONS;

() {
	setopt LOCAL_OPTIONS LOCAL_TRAPS;

	local SF=${(%):-%x};
	local SD=${SF:h};

	source "$ZEX_DIR/lib/scripts.zsh" 2>/dev/null ||
		{ echo "Could not source zsh-ex/lib/scripts.zsh, is zsh-ex installed?"; exit 1; }

##																									\e[m
##	cdt [options]
##		Creates a temporary directory and cd's into it, temporary directories are not cleaned
## 		automatically.
##																									\e[m
##		\e[31;1moptions\e[m
##			-h		  Shows this help information
##			-v		  Increases verbosity, may be repeated multiple times
##

	# Parse the options passed in, this needs to match the options listed in the help file, see `man zshmodule` for details
	zparseopts -D -E v+=VERBOSITY h=HELP ||
		help;

	# Capture the verbosity number (number of -vvv's)
	VERBOSITY=${#VERBOSITY}

	# Display help if requested
	[[ "$HELP" ]] &&
		help;

	mkdir -p ~/tmp;

	# Called on exit from this point forward
	on_exit() {

	}
	trap on_exit EXIT;

	# Command code starts here
	DIR=$(mktemp -p ~/tmp/ -d `date +%Y%m%d-%H%M`-XXXXXX);

	cd "$DIR";

} "$@";
